[2025-02-08 18:37:35][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:36][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:37][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:38][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:39][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:40][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:40][MAIN] - Traceback (most recent call last):
[2025-02-08 18:37:40][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 89, in <module>
[2025-02-08 18:37:40][MAIN] - main()
[2025-02-08 18:37:40][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 77, in main
[2025-02-08 18:37:40][MAIN] - time.sleep(0.5)
[2025-02-08 18:37:40][MAIN] - KeyboardInterrupt
[2025-02-08 18:37:41][MAIN] - IP 84.150.103.227 uploaded to:
[2025-02-08 18:37:41][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-02-08 18:37:41][MAIN] - Exception ignored in: 
[2025-02-08 18:37:41][MAIN] - <module 'threading' from '/usr/lib/python3.10/threading.py'>
[2025-02-08 18:37:41][MAIN] - Traceback (most recent call last):
[2025-02-08 18:37:41][MAIN] -   File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
[2025-02-08 18:37:41][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:41][MAIN] - lock.acquire()
[2025-02-08 18:37:41][MAIN] - KeyboardInterrupt
[2025-02-08 18:37:41][MAIN] - : 
[2025-02-08 18:37:41][FLASK] -  * Serving Flask app 'server'
[2025-02-08 18:37:41][FLASK] -  * Debug mode: off
[2025-02-08 18:37:41][WEBSOCKET] - Process Process-3:
[2025-02-08 18:37:41][WEBSOCKET] - Traceback (most recent call last):
[2025-02-08 18:37:41][WEBSOCKET] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap

[2025-02-08 18:37:41][WEBSOCKET] -     self.run()
[2025-02-08 18:37:41][WEBSOCKET] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run

[2025-02-08 18:37:41][WEBSOCKET] -     self._target(*self._args, **self._kwargs)
[2025-02-08 18:37:41][WEBSOCKET] -   File "/home/claudio/Python-Projects/RoomServer/websocket.py", line 70, in start_websocket

[2025-02-08 18:37:41][WEBSOCKET] -     socketio.run(app, host='0.0.0.0', port=HOSTNAME['websocket_port'])
[2025-02-08 18:37:41][WEBSOCKET] -   File "/home/claudio/Python-Projects/RoomServer/.venv/lib/python3.10/site-packages/flask_socketio/__init__.py", line 651, in run

[2025-02-08 18:37:41][WEBSOCKET] -     raise RuntimeError('The Werkzeug web server is not '
[2025-02-08 18:37:41][WEBSOCKET] - RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.
[2025-02-08 18:37:42][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 18:37:42][MAIN] - Exception ignored in atexit callback
[2025-02-08 18:37:42][MAIN] - : 
[2025-02-08 18:37:42][MAIN] - <function _exit_function at 0x7f45dc4e2b90>
[2025-02-08 18:37:42][MAIN] - Traceback (most recent call last):
[2025-02-08 18:37:42][MAIN] -   File "/usr/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
[2025-02-08 18:37:42][MAIN] - p.join()
[2025-02-08 18:37:42][MAIN] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
[2025-02-08 18:37:42][MAIN] - res = self._popen.wait(timeout)
[2025-02-08 18:37:42][MAIN] -   File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
[2025-02-08 18:37:42][MAIN] - return self.poll(os.WNOHANG if timeout == 0.0 else 0)
[2025-02-08 18:37:42][MAIN] -   File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
[2025-02-08 18:37:42][MAIN] - pid, sts = os.waitpid(self.pid, flag)
[2025-02-08 18:37:42][MAIN] - KeyboardInterrupt
[2025-02-08 18:37:42][MAIN] - : 
